"""
orvue_us_inverse.reports.manual - build the user manual (PDF) from the code.

    python -m orvue_us_inverse manual          -> docs/Ultrasound Inverse Anatomy Mapping - User Manual.pdf
    python -m orvue_us_inverse.reports.manual out.pdf

Layout: the Orvue Surgical template (reports.pdf_template). Read defaults and parameters from the code, so the
manual follows the code.
"""
import os
import sys
import time

from orvue_us_inverse import __version__
from orvue_us_inverse.__main__ import COMMANDS, MENU
from orvue_us_inverse.paths import MANUAL_PDF, SETTINGS_PATH
from orvue_us_inverse.core.example import load_settings
from orvue_us_inverse.reports.pdf_template import Doc, code_inline as C

TITLE = "Ultrasound Inverse Anatomy Mapping - User Manual"


def build(path=MANUAL_PDF):
    d = Doc(path, title=TITLE, subtitle="Installation, use and parameters",
            footer=f"generated by orvue_us_inverse.reports.manual (version {__version__})")
    d.cover(lines=[f"Version {__version__} &nbsp;|&nbsp; {time.strftime('%d %B %Y')}",
                   "Generated from the code by orvue_us_inverse.reports.manual"])
    d.toc()
    d.h1("1. Installation")
    d.p("Python 3.10 or later. Install once in the project's conda environment:")
    d.code("pip install -r requirements.txt\npip install -e .")
    d.h1("2. Use")
    d.p(f"Run {C('python -m orvue_us_inverse')} to open the Ultrasound Imaging Simulator: one window for "
        "everything. The case selector and 'Calibrate probe' are in its header (the calibration runs in the same "
        "window); the IMAGING MODE tabs B-MODE and INVERSE MAPPING (Tab switches) are in the left panel. The inverse "
        "mapping takes its pose from a scripted sweep, the mouse or the camera-tracked probe (SPACE or RECORD "
        "switches recording on / off), shows the 3D reconstruction and projects the structures found onto the live "
        "camera view (AR overlay).")
    d.p(f"Developer tools: {C('python -m orvue_us_inverse dev')} (menu below) or "
        f"{C('python -m orvue_us_inverse &lt;command&gt;')}.")
    d.table([["No.", "Step", "What it does", "Command"]]
            + [[num, name, what, cmd] for _, num, name, what, cmd, _ in MENU])
    d.h1("3. Settings")
    d.p(f"{C(os.path.relpath(SETTINGS_PATH, os.path.dirname(os.path.dirname(SETTINGS_PATH))))}:")
    d.table([["Key", "Value"]] + [[k, str(v)] for k, v in load_settings().items()])
    d.p(f"Commands: {', '.join(COMMANDS)}.")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return d.build()


if __name__ == "__main__":
    print("wrote", build(sys.argv[1] if len(sys.argv) > 1 else MANUAL_PDF))
