"""
orvue_us_inverse.reports.pdf_template - Orvue Surgical PDF template (reportlab), shared by every PDF this project generates.

Look: A4 portrait, Orvue Surgical logo and company name top left with the document title under it, a teal rule
under the header, "Page n of N" footer, teal headings, compact grey-gridded tables with a pale teal header row,
figures with numbered captions, code blocks, note boxes and an optional cover page and table of contents.

    from orvue_us_inverse.reports.pdf_template import Doc
    doc = Doc("out.pdf", title="My document", subtitle="what it is", footer="generated by my_script.py")
    doc.cover(lines=["Version ...", "Date ..."], image="docs/images/x.png")     # optional
    doc.toc()                                                                     # optional
    doc.h1("1. Section"); doc.p("Text with <b>markup</b>."); doc.table([...], widths=[...])
    doc.figure("image.png", "Caption", width_mm=170); doc.code("python x.py"); doc.note("Tip ...")
    doc.build()

Used by reports.manual. Keep new PDFs on this template so they all look the same.
"""
import os
import time

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.platypus import (BaseDocTemplate, CondPageBreak, Frame, Image, KeepTogether, PageBreak, PageTemplate,
                                Paragraph, Preformatted, Spacer, Table, TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents

from orvue_us_inverse.paths import LOGO_PATH as LOGO  # noqa: E402
COMPANY = "Orvue Surgical"

# ---------------------------------------------------------------- colours and styles
TEAL = colors.Color(0.03, 0.31, 0.25)            # Orvue teal (headings, rules)
TEAL_LIGHT = colors.Color(0.90, 0.93, 0.92)      # table header / note background
AMBER = colors.Color(1.0, 0.71, 0.0)             # accent, as in the clinical display
GRID = colors.Color(0.70, 0.70, 0.70)
GREY = colors.Color(0.30, 0.30, 0.30)
STRIPE = colors.Color(0.97, 0.97, 0.97)
PAGE_W, PAGE_H = A4
MARGIN = 15 * mm
CONTENT_W = PAGE_W - 2 * MARGIN

_ST = getSampleStyleSheet()
TITLE = ParagraphStyle("o_title", parent=_ST["Heading1"], fontSize=15, textColor=TEAL, spaceBefore=0, spaceAfter=4)
H1 = ParagraphStyle("o_h1", parent=_ST["Heading2"], fontSize=12.5, textColor=TEAL, spaceBefore=10, spaceAfter=4)
H2 = ParagraphStyle("o_h2", parent=_ST["Heading3"], fontSize=10, textColor=TEAL, spaceBefore=7, spaceAfter=2)
H3 = ParagraphStyle("o_h3", parent=_ST["Heading4"], fontSize=8.8, textColor=GREY, spaceBefore=5, spaceAfter=1)
BODY = ParagraphStyle("o_body", parent=_ST["BodyText"], fontSize=8.4, leading=11.2, spaceAfter=3)
SMALL = ParagraphStyle("o_small", parent=BODY, fontSize=7.2, leading=9.2)
CELL = ParagraphStyle("o_cell", parent=BODY, fontSize=7, leading=8.6, spaceAfter=0)
CELL_B = ParagraphStyle("o_cell_b", parent=CELL, fontName="Helvetica-Bold")
CAPTION = ParagraphStyle("o_caption", parent=SMALL, textColor=GREY, alignment=TA_CENTER, spaceBefore=2,
                         spaceAfter=8)
BULLET = ParagraphStyle("o_bullet", parent=BODY, leftIndent=11, bulletIndent=2, spaceAfter=1.5)
CODE = ParagraphStyle("o_code", fontName="Courier", fontSize=7.4, leading=9.2, textColor=colors.black)
TOC1 = ParagraphStyle("o_toc1", parent=BODY, fontName="Helvetica-Bold", fontSize=8.8, leading=12, leftIndent=0)
TOC2 = ParagraphStyle("o_toc2", parent=BODY, fontSize=8, leading=10.5, leftIndent=12)


def code_inline(s):
    """Inline code markup for Paragraph text."""
    return f"<font face='Courier' size='7.8'>{s}</font>"


# ---------------------------------------------------------------- page decoration
class _NumberedCanvas(rl_canvas.Canvas):
    """Header and 'Page n of N' footer on every page except the cover (page 1 when the document has one)."""
    title, footer, has_cover = "", "", False

    def __init__(self, *a, **k):
        super().__init__(*a, **k)
        self._pages = []

    def showPage(self):
        self._pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        n = len(self._pages)
        for st in self._pages:
            self.__dict__.update(st)
            if not (self.has_cover and self._pageNumber == 1):
                self._decorate(n)
            super().showPage()
        super().save()

    def _decorate(self, total):
        if os.path.exists(LOGO):
            self.drawImage(LOGO, MARGIN, PAGE_H - 20 * mm, 11 * mm, 11 * mm)
        self.setFont("Helvetica-Bold", 10)
        self.setFillColor(colors.black)
        self.drawString(29 * mm, PAGE_H - 13.5 * mm, COMPANY)
        self.setFont("Helvetica", 8)
        self.setFillColor(GREY)
        self.drawString(29 * mm, PAGE_H - 18 * mm, self.title)
        self.setStrokeColor(TEAL)
        self.setLineWidth(0.6)
        self.line(MARGIN, PAGE_H - 22 * mm, PAGE_W - MARGIN, PAGE_H - 22 * mm)
        self.setFont("Helvetica", 7)
        self.drawString(MARGIN, 10 * mm, f"{COMPANY} - {self.footer}" if self.footer else COMPANY)
        self.drawRightString(PAGE_W - MARGIN, 10 * mm, f"Page {self._pageNumber} of {total}")


class _DocTemplate(BaseDocTemplate):
    """Registers H1 / H2 headings with the table of contents and as PDF bookmarks."""

    def afterFlowable(self, flowable):
        if isinstance(flowable, Paragraph) and flowable.style.name in ("o_h1", "o_h2"):
            level = 0 if flowable.style.name == "o_h1" else 1
            text = flowable.getPlainText()
            key = f"h{id(flowable)}"
            self.canv.bookmarkPage(key)
            self.canv.addOutlineEntry(text, key, level=level, closed=level > 0)
            self.notify("TOCEntry", (level, text, self.page, key))


# ---------------------------------------------------------------- document builder
class Doc:
    """Collects flowables and builds the PDF in the Orvue Surgical template."""

    def __init__(self, path, title, subtitle="", footer="", author=COMPANY):
        self.path, self.title, self.subtitle, self.footer, self.author = path, title, subtitle, footer, author
        self.story, self.has_cover, self.fig_no, self.has_toc = [], False, 0, False

    # ---- front matter
    def cover(self, lines=(), image=None, image_width_mm=150):
        """Cover page: large logo, company, title, subtitle, optional image and info lines."""
        self.has_cover = True
        s = self.story
        s.append(Spacer(1, 30 * mm))
        if os.path.exists(LOGO):
            s.append(Image(LOGO, 32 * mm, 32 * mm))
        s.append(Spacer(1, 6 * mm))
        s.append(Paragraph(COMPANY, ParagraphStyle("c_co", parent=BODY, fontSize=13, textColor=GREY,
                                                   alignment=TA_CENTER, fontName="Helvetica-Bold")))
        s.append(Spacer(1, 4 * mm))
        s.append(Paragraph(self.title, ParagraphStyle("c_t", parent=TITLE, fontSize=22, leading=27,
                                                      alignment=TA_CENTER)))
        if self.subtitle:
            s.append(Paragraph(self.subtitle, ParagraphStyle("c_s", parent=BODY, fontSize=11, leading=15,
                                                             textColor=GREY, alignment=TA_CENTER)))
        s.append(Spacer(1, 8 * mm))
        if image and os.path.exists(image):
            s.append(_scaled_image(image, image_width_mm * mm, 105 * mm))
            s.append(Spacer(1, 6 * mm))
        for line in lines:
            s.append(Paragraph(line, ParagraphStyle("c_l", parent=BODY, fontSize=9, alignment=TA_CENTER,
                                                    textColor=GREY)))
        s.append(PageBreak())

    def toc(self, heading="Contents"):
        self.has_toc = True
        t = TableOfContents()
        t.levelStyles = [TOC1, TOC2]
        t.dotsMinLevel = 0
        self.story += [Paragraph(heading, TITLE), Spacer(1, 2 * mm), t, PageBreak()]

    # ---- text
    def title_block(self, info=""):
        """Title at the top of the first content page (for documents without a cover)."""
        self.story.append(Paragraph(self.title, TITLE))
        self.story.append(Paragraph(info or f"{COMPANY} &nbsp;|&nbsp; generated {time.strftime('%Y-%m-%d %H:%M')}",
                                    BODY))
        self.story.append(Spacer(1, 3))

    def h1(self, text, new_page=False):
        if new_page:
            self.story.append(PageBreak())
        else:
            self.story.append(CondPageBreak(40 * mm))
        self.story.append(Paragraph(text, H1))

    def h2(self, text):
        self.story.append(CondPageBreak(25 * mm))
        self.story.append(Paragraph(text, H2))

    def h3(self, text):
        self.story.append(Paragraph(text, H3))

    def p(self, text, style=BODY):
        self.story.append(Paragraph(text, style))

    def small(self, text):
        self.p(text, SMALL)

    def bullets(self, items, style=BULLET):
        for it in items:
            self.story.append(Paragraph(it, style, bulletText="•"))

    def steps(self, items):
        for i, it in enumerate(items, 1):
            self.story.append(Paragraph(it, BULLET, bulletText=f"{i}."))

    def code(self, text):
        """Monospaced block on a pale background."""
        pre = Preformatted(text.strip("\n"), CODE)
        t = Table([[pre]], colWidths=[CONTENT_W])
        t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), colors.Color(0.95, 0.96, 0.96)),
                               ("BOX", (0, 0), (-1, -1), 0.3, GRID),
                               ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                               ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]))
        self.story += [t, Spacer(1, 4)]

    def note(self, text, label="Note"):
        """Highlighted note box with a teal bar."""
        body = Paragraph(f"<b>{label}.</b> {text}", BODY)
        t = Table([["", body]], colWidths=[1.6 * mm, CONTENT_W - 1.6 * mm])
        t.setStyle(TableStyle([("BACKGROUND", (0, 0), (0, 0), TEAL), ("BACKGROUND", (1, 0), (1, 0), TEAL_LIGHT),
                               ("LEFTPADDING", (1, 0), (1, 0), 6), ("RIGHTPADDING", (1, 0), (1, 0), 6),
                               ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                               ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
        self.story += [Spacer(1, 2), t, Spacer(1, 5)]

    def space(self, h_mm=3):
        self.story.append(Spacer(1, h_mm * mm))

    def page_break(self):
        self.story.append(PageBreak())

    # ---- tables and figures
    def table(self, rows, widths=None, header_rows=1, font_size=7, keep=False, wrap=True):
        """Gridded table; strings are wrapped into Paragraphs (bold in header rows). widths in points
        (multiply mm values by reportlab.lib.units.mm); default: equal widths over the page."""
        n = max(len(r) for r in rows)
        widths = widths or [CONTENT_W / n] * n
        data = []
        for i, r in enumerate(rows):
            style = CELL_B if i < header_rows else CELL
            data.append([Paragraph(str(c), style) if wrap and isinstance(c, str) else c for c in r])
        t = Table(data, colWidths=widths, repeatRows=header_rows)
        t.setStyle(TableStyle([
            ("FONT", (0, 0), (-1, -1), "Helvetica", font_size),
            ("BACKGROUND", (0, 0), (-1, header_rows - 1), TEAL_LIGHT),
            ("GRID", (0, 0), (-1, -1), 0.25, GRID),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ROWBACKGROUNDS", (0, header_rows), (-1, -1), [colors.white, STRIPE]),
            ("TOPPADDING", (0, 0), (-1, -1), 1.8), ("BOTTOMPADDING", (0, 0), (-1, -1), 1.8),
            ("LEFTPADDING", (0, 0), (-1, -1), 3), ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ]))
        self.story += [KeepTogether([t]) if keep else t, Spacer(1, 5)]
        return t

    def figure(self, path, caption, width_mm=170, max_height_mm=200):
        """Image scaled to width (and at most max_height), with a numbered caption; kept together."""
        if not os.path.exists(path):
            self.p(f"<i>[missing figure: {os.path.basename(path)}]</i>", SMALL)
            return
        self.fig_no += 1
        img = _scaled_image(path, width_mm * mm, max_height_mm * mm)
        self.story.append(KeepTogether([img, Paragraph(f"<b>Figure {self.fig_no}.</b> {caption}", CAPTION)]))

    def add(self, flowable):
        self.story.append(flowable)

    # ---- output
    def build(self):
        canvas_cls = type("Canvas", (_NumberedCanvas,), dict(title=self.title, footer=self.footer,
                                                              has_cover=self.has_cover))
        doc = _DocTemplate(self.path, pagesize=A4, leftMargin=MARGIN, rightMargin=MARGIN, topMargin=26 * mm,
                           bottomMargin=16 * mm, title=self.title, author=self.author, subject=self.subtitle)
        frame = Frame(MARGIN, 16 * mm, CONTENT_W, PAGE_H - 42 * mm, id="body")
        doc.addPageTemplates([PageTemplate(id="page", frames=[frame])])
        if self.has_toc:
            doc.multiBuild(list(self.story), canvasmaker=canvas_cls)
        else:
            doc.build(list(self.story), canvasmaker=canvas_cls)
        return self.path


def _scaled_image(path, max_w, max_h):
    from reportlab.lib.utils import ImageReader
    iw, ih = ImageReader(path).getSize()
    s = min(max_w / iw, max_h / ih)
    return Image(path, iw * s, ih * s)
